server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
        defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: apigateway-service
  cloud:
      gateway:
        routes:
          - id: first-service
            uri: http://localhost:8081
            predicates:
              - Path=/first-service/**
            # request 와 response 에 header 를 추가하는 필터
            filters:
#              - AddRequestHeader=first-request, first-request-header2
#              - AddResponseHeader=first-response, first-response-header2
              - CustomFilter
          - id: second-service
            uri: http://localhost:8082
            predicates:
              - Path=/second-service/**
            filters:
#                - AddRequestHeader=second-request, second-request-header2
#                - AddResponseHeader=second-response, second-response-header2
              - CustomFilter
