server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suman-kim/spring-cloud-msa
          search-paths: yml-file
          default-label: main
